name: "Terraform Infrastructure DESTROY Pipeline with GitHub Actions"

on: 
  workflow_dispatch:

env: 
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET_NAME: tfstate-bucket-rhai-poc
  AWS_REGION: us-east-2

jobs:
  destroy:
    name: "Terraform Infrastructure DESTRUCTION"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./terraform

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
      - name: Configure user_data and/or remote_exec provisioner
        run: |
          perl -pi -e 's/<organization_ID>/${{ secrets.ORG_ID }}/' main.tf
          perl -pi -e 's/<activation_key_name>/${{ secrets.ACTIVATION_KEY }}/' main.tf
          perl -pi -e 's/<source_ip>/${{ secrets.SOURCE_IP }}/g' main.tf
          perl -pi -e 's/<S3_BUCKET_NAME>/${{ env.S3_BUCKET_NAME }}/g' main.tf
          perl -pi -e 's/<AWS_REGION>/${{ env.AWS_REGION }}/g' main.tf

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=${{ env.S3_BUCKET_NAME }}"

      - name: Destroy Infrastructure
        run: terraform destroy -auto-approve

      - name: Empty S3 bucket
        run: |
          aws --region ${{ env.AWS_REGION }} s3 rm s3://${{ env.S3_BUCKET_NAME }} --recursive

      - name: Delete S3 bucket
        run: |
          aws --region ${{ env.AWS_REGION }} s3api delete-bucket --bucket ${{ env.S3_BUCKET_NAME }} --force